services:
    tag.form.type.tags:
        class: FaimfonyBundle\Form\TagsType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type }

    meal.form.type.usermeal:
        class: FaimfonyBundle\Form\UserMealType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type }
